CREATE USER IF NOT EXISTS 'fabi-cc'@'%' IDENTIFIED BY 'fabiola';
GRANT ALL PRIVILEGES ON blog_fabiola.* TO 'fabi-cc'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    book_title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    genre VARCHAR(200) NOT NULL,
    sinopsis TEXT NOT NULL,
    comments TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

INSERT INTO users (user, password) VALUES ('admin', '827ccb0eea8a706c4c34a16891f84e7b');